server:
  port: 8088

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        service-name: product-service
        instance-id: ${spring.application.name}:${server.port}

  application:
    name: product-service
  datasource:
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5442/product
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
